spring.application.name=notification-service
spring.config.import=optional:configserver:http://localhost:8888

server.port=8083

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest